---
services:
  frontend:
    build:
      context: ./vite-project
      dockerfile: Dockerfile
    volumes:
      - ./vite-project:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
    - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: npm run dev
    
  backend:
    build:
      context: ./jobtracker
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tty: true

volumes:
  node_modules:
  postgres_data:
    driver: local
